### ISSUE TITLE
ERROR: Failed to resolve: com.github.mayuce:AndroidDocumentScanner:1.4

### ISSUE THREAD

**Issue by yogesh-ala** [mayuce/AndroidDocumentScanner#1]
ERROR: Failed to resolve: com.github.mayuce:AndroidDocumentScanner:1.4
Show in Project Structure dialog
Affected Modules: app

Android studio 3.5
compileSdkVersion 28

**Comment by mayuce** [comment]
Have you done this step ? 
Add this " maven { url "https://jitpack.io" } " line to top level of your project and try to sync gradle again, it'll work ✅
allprojects {
    repositories {
        /// ....
        maven { url "https://jitpack.io" }
    }
}

**Comment by yogesh-ala** [comment]
Thanks it's working now.
