### ISSUE TITLE
Function invertColor not working

### ISSUE THREAD

**Issue by EzequielMessore** [mayuce/AndroidDocumentScanner#12]
Hello, I have a problem with the function `invertColor`, when I invert the for gray scale and crop the imagem i cannot `invertColor` again and get the original color with the image already cropped.

Could you help me?

**Comment by mayuce** [comment]
I couldn't understand your problem. What I understand is you're inverting color then you want to make image colorful again but you couldn't. Is that true?

**Comment by EzequielMessore** [comment]
Yes is this, but this only happens when you crop the image on gray scale.

**Comment by EzequielMessore** [comment]
do you have any idea ?

**Comment by mayuce** [comment]
I'll look for it, i couldn't had a time for it 🙁

**Comment by mayuce** [comment]
Thanks @bagolysz for his contribution!
