### ISSUE TITLE
Can't find DocumentScanActivity

### ISSUE THREAD

**Issue by javierhinmel** [mayuce/AndroidDocumentScanner#13]
Hi, I want to use this library for a Test project. I'm using version 1.5.1. Here my gradle dependencies:

![image](https://user-images.githubusercontent.com/60926533/83170977-c02aa380-a0eb-11ea-9ff5-e24cededb77d.png)

Follow the tutorial. It says 
![image](https://user-images.githubusercontent.com/60926533/83171206-244d6780-a0ec-11ea-81c9-840f76e95eb8.png)

but when I want to extends my Activity from DocumentScannerActivity (or DocumentScanActivity. I found in the library), Android Studio does not recognize it.

![image](https://user-images.githubusercontent.com/60926533/83171612-bfded800-a0ec-11ea-94a3-f1e66c851807.png)

Please, help me. Thank you!

**Comment by mayuce** [comment]
Hello Javier, that is because of ProGuard, I'll fix it and release new version today. Thanks for feedback.

**Comment by mayuce** [comment]
Now you can feed your app with 1.5.2 version. Enjoy it.!

**Comment by javierhinmel** [comment]
Thank you @mayuce !!!

**Comment by mayuce** [comment]
> Thank you @mayuce !!!

You're welcome 😊
