### ISSUE TITLE
Any way to configure/keep original quality? (Quality makes documents unreadable)

### ISSUE THREAD

**Issue by Merthan** [mayuce/AndroidDocumentScanner#2]
Quality gets noticably worse when going from Camera to the Cropper, rotation is also always wrong (always turned 90° to the left on Pixel 3a, compared to the camera picture)

**Comment by mayuce** [comment]
Yes it is possible but I need a time to do it but nowadays I'm super busy, that's why it seems like gonna take a while to do it. But you can fork project and develop your own or you can do it on another branch and send a Pull Request to merge, I'll look it 😊

**Comment by Merthan** [comment]
Nvm my fault, the bitmap that I received itself was low quality, should have checked that myself
So yeah... sorry for making you think there was any problem there

Regarding the rotation: It is only wrong when the device is in portrait mode, otherwise it's correct and it also only affects the initial orientation of the preview.

Images from the camera should always have rotation data [like here](https://stackoverflow.com/questions/7286714/android-get-orientation-of-a-camera-bitmap-and-rotate-back-90-degrees) so I can just do if else with portrait or non portrait and rotate accordingly myself, probably also the reason why you didn't do it in the first place (Bitmaps don't have rotation data and you only receive a Bitmap)

So yeah, there isn't even a good way to solve it in my opinion, you could in theory include a variable for rotation in Scannerconstants or take a File/File Path itself which would include rotation data, but even then not everyone would have a file.

So... there isn't any issue here, everything about this library was perfect from the beginning ;D.
