### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by akshitpsutariya** [mayuce/AndroidDocumentScanner#21]
Thank you Brother, for help to Making my Application more Beautiful 🙏🙏🙏.

![WhatsApp Image 2020-07-11 at 2 05 16 PM](https://user-images.githubusercontent.com/41141999/87220238-c74a0000-c37f-11ea-820d-229f686c121d.jpeg)

**Comment by mayuce** [comment]
You're welcome, happy to see you've done it :)
