### ISSUE TITLE
issue in loading large resolution images

### ISSUE THREAD

**Issue by Ashni5** [mayuce/AndroidDocumentScanner#27]
when i try to load large resolution images  app crash.without reducing quality of image unable to load image(error is not displaying in logcat)

**Comment by vasep** [comment]
im encountering the same issue:
-void org.opencv.imgproc.Imgproc.resize_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_resize_13 and Java_org_opencv_imgproc_Imgproc_resize_13__JJDD) // liv 4.1

**Comment by mayuce** [comment]
That is actually what you need to do passing the bitmap to the scanner. You should reduce the size by using any method and then you're okay to pass the value.
