### ISSUE TITLE
Compatibility with OpenCV 4.3.0

### ISSUE THREAD

**Issue by thelittlefireman** [mayuce/AndroidDocumentScanner#30]
hi,
for now your library is compatible with OpenCV 3.4.1, could it be possible to make it compatible with OpenCV 4.3.X which is an upgrade in terms of performance and a more compress library ?
[https://github.com/quickbirdstudios/opencv-android](https://github.com/quickbirdstudios/opencv-android)

Thanks for all

**Comment by mayuce** [comment]
I'll take a look at that next weekend (hopefully)

**Comment by raqfc** [comment]
> I'll take a look at that next weekend (hopefully)

Any updates on this??

**Comment by mayuce** [comment]
With `1.6.0` version it has been updated to `openCV 4.5.2`!
