### ISSUE TITLE
APK Size is above 60 MB?

### ISSUE THREAD

**Issue by solankiranvir** [mayuce/AndroidDocumentScanner#4]
Hello
When i use your library for detecting edges apk size is above 60MB due to openCV so how to reduce it nearly 35-40MB?
Any solution?

**Comment by Awais-Ali** [comment]
Try split apk or create bundle to upload on play store, it will auto generate according to the device

**Comment by mayuce** [comment]
You can check answer below
https://stackoverflow.com/a/45074929/8095053
