### ISSUE TITLE
Android 9 - Fatal Exception: java.lang.UnsatisfiedLinkError dlopen failed: file offset for the library "/data/app/com.package-uEoPlhZ_ICGDWQ5Rsg_naA==/lib/arm/libopencv_java3.so" >= file size: 0 >= 0

### ISSUE THREAD

**Issue by Awais-Ali** [mayuce/AndroidDocumentScanner#5]
java.lang.Runtime.loadLibrary0 + 1016 (Runtime.java:1016)
--
  | java.lang.System.loadLibrary + 1669 (System.java:1669)
  | com.ceuwallet.ceuwallet.documentscanner.libraries.NativeClass.<clinit> + 27 (NativeClass.java:27)

![1234](https://user-images.githubusercontent.com/7523476/70848043-d8846a00-1e8d-11ea-99ff-f6ac50dd192b.png)
![1234](https://user-images.githubusercontent.com/7523476/70848059-fc47b000-1e8d-11ea-9080-03918402ae92.png)

**Comment by mayuce** [comment]
Hello Ali, I see your problem but I don't have any idea about it; you should Google it but you may having a trouble about implementing OpenCV module.
