### ISSUE TITLE
Change language of buttons on ImageCropActivity screen. 

### ISSUE THREAD

**Issue by zohaib962** [mayuce/AndroidDocumentScanner#6]
Hello.. Is there anyway to change button design or language of ImageCropActivity screen?

**Comment by mayuce** [comment]
Hi, yes it's possible to change the language of activity. You should read the readme on landing page first 😀 But you can't change the design of the library. You can change it by adding as a module the library and configure it how you desired. When I've time I'll make some abstractions and interfaces about it then you'll have chance to design it by yourself.
