### ISSUE TITLE
Update 1.5 Has ScannerConstants missing

### ISSUE THREAD

**Issue by geferon** [mayuce/AndroidDocumentScanner#8]
I've managed to install this library correctly, both using 1.4 and 1.5

1.4 uses the following namespace:

```java
import team.clevel.documentscanner.ImageCropActivity;
import team.clevel.documentscanner.helpers.ScannerConstants;
```

while 1.5 uses:

```java
import com.labters.documentscanner.ImageCropActivity;
import com.labters.documentscanner.helpers.ScannerConstants;
```

But, for some reason, in the version 1.5, the Helpers namespace has NOTHING in it, or at least nothing accessible to the public.
Comparison here:
![image](https://user-images.githubusercontent.com/7958349/76760268-9f5ddd80-678d-11ea-8d17-fe6540d93828.png)

1.4:
![image](https://user-images.githubusercontent.com/7958349/76760344-c3b9ba00-678d-11ea-80c8-d7f4cb9fe63c.png)

I don't know what went wrong during the version being published, but this problem basically doesn't allow one to use it, as you need to access the ScannerConstants class to get/set the image.

**Comment by mayuce** [comment]
Sorry for delay because I was at the military. This issue was about proguard, fixed on a756fc150f464e871048bf63a1824de1b7fa03cd commit.You can get it by changing version of the library version to 1.5.1.
