### ISSUE TITLE
Edge detection not working sometimes.

### ISSUE THREAD

**Issue by ganeh04** [mayuce/AndroidDocumentScanner#9]
I had implemented this library in one of my project with the help of library I want to detect the id prof cards every thing is working fine but the problem is when card was placed on multicoloured background the edges of the card are not getting exactly identified in the sense the polygon view which allows the user to crop is getting applied to full background. Please help me to solve this issue

**Comment by mayuce** [comment]
Can you show us the image which is you wanted to crop?

**Comment by ganeh04** [comment]
Hi,

The following are the images which i wanted to detect the edges. In that image i just want to detect the edges of the card alone but the polygon view got applied for the whole image
![Screenshot_2020_0618_195539](https://user-images.githubusercontent.com/62432603/85032780-d92fed00-b19d-11ea-8958-c2736fae043e.jpg)

**Comment by mayuce** [comment]
Yes it's a possibility, this library doesn't guarantees to work like a charm on every image 😄. If you try it with CamScanner, you'd probably get the same result.

**Comment by birjubhatt** [comment]
users need to change background 
please put your document in even colour surface ...like black or white..and try...maybe this work
